version: '3.8'

services:
  db:
    image: mysql:8.0  #ใช้ 8.0 เพื่อความทันสมัย
    container_name: mysql_db_700
    # MySql 8.0 ใช้ plugin ตัวใหม่ จึงต้องใช้คำสั่งนี้เพื่อให้เข้ากับ client เก่าได้ดีขึ้น
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "8700:3306"
    volumes:
      - mysql_data_700:/var/lib/mysql
    networks:
      - weblab700
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_700
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 64M
    ports:
      - "8701:80"
    depends_on:
      - db #รัน phpmyadmin ได้ก็ต่อเมื่อ db ต้อง on ก่อน
    networks:
      - weblab700
    restart: always

networks:
  weblab700:
    driver: bridge

volumes:
  mysql_data_700:
    driver: local